# Generated by Django 3.2.9 on 2021-12-16 12:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('proficiency', models.CharField(choices=[('amateur', 'amateur'), ('professional', 'professional')], default=None, max_length=30)),
                ('age_group', models.CharField(choices=[('UNDER-19', 'UNDER-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54'), ('55-59', '55-59'), ('60-64', '60-64'), ('65-OVER', '65-OVER')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organiser', models.CharField(max_length=255)),
                ('distance', models.IntegerField(choices=[(1, 'Super Sprint'), (2, 'Sprint'), (3, 'Olimpijski'), (4, '1/4'), (5, '1/2'), (6, 'Ironman')])),
                ('date', models.DateField(default=datetime.date.today)),
                ('city', models.CharField(max_length=255)),
                ('voivodeship', models.CharField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('race_url', models.URLField()),
                ('participants', models.ManyToManyField(to='TriEvent_app.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonim', max_length=120)),
                ('rating', models.IntegerField(choices=[(1, 'słabo'), (2, 'tak sobie'), (3, 'OK'), (4, 'fajnie'), (5, 'rewelacja')])),
                ('comment', models.TextField(max_length=500)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.race')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swim', models.TimeField()),
                ('T1', models.TimeField()),
                ('bike', models.TimeField()),
                ('T2', models.TimeField()),
                ('run', models.TimeField()),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.athlete')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.race')),
            ],
        ),
    ]
