# Generated by Django 3.2.9 on 2021-12-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(choices=[('Super Sprint', 'Super Sprint'), ('Sprint', 'Sprint'), ('Olimpijski', 'Olimpijski'), ('1/4', '1/4'), ('1/2', '1/2'), ('Ironman', 'Ironman')]),
        ),
        migrations.AlterField(
            model_name='race',
            name='voivodeship',
            field=models.CharField(choices=[('dolnośląskie', 'dolnośląskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('łódzkie', 'łódzkie'), ('małopolskie', 'małopolskie'), ('mazowieckie', 'mazowieckie'), ('opolskie', 'opolskie'), ('podkarpackie', 'podkarpackie'), ('podlaskie', 'podlaskie'), ('pomorskie', 'pomorskie'), ('śląskie', 'śląskie'), ('świętokrzyskie', 'świętokrzyskie'), ('warmińsko-mazurskie', 'warmińsko-mazurskie'), ('wielkopolskie', 'wielkopolskie'), ('zachodniopomorskie', 'zachodniopomorskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('słabo', 'słabo'), ('tak sobie', 'tak sobie'), ('OK', 'OK'), ('fajnie', 'fajnie'), ('rewelacja', 'rewelacja')]),
        ),
    ]
