# Generated by Django 3.2.9 on 2021-12-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0002_auto_20211219_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(choices=[(1, 'Super Sprint'), (2, 'Sprint'), (3, 'Olimpijski'), (4, '1/4'), (5, '1/2'), (6, 'Ironman')]),
        ),
        migrations.AlterField(
            model_name='race',
            name='participants',
            field=models.ManyToManyField(default=None, to='TriEvent_app.Athlete'),
        ),
        migrations.AlterField(
            model_name='race',
            name='voivodeship',
            field=models.CharField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'słabo'), (2, 'tak sobie'), (3, 'OK'), (4, 'fajnie'), (5, 'rewelacja')]),
        ),
    ]
