# Generated by Django 3.2.9 on 2021-11-23 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=60)),
                ('proficiency', models.CharField(choices=[(1, 'amateur'), (2, 'professional')], default=None, max_length=30)),
                ('age_group', models.CharField(choices=[(1, 'UNDER-19'), (2, '20-24'), (3, '25-29'), (4, '30-34'), (5, '35-39'), (6, '40-44'), (7, '45-49'), (8, '50-54'), (9, '55-59'), (10, '60-64'), (11, '65-OVER')], max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organiser', models.CharField(max_length=255)),
                ('distance', models.IntegerField(choices=[(1, 'Super Sprint'), (2, 'Sprint'), (3, 'Olimpijski'), (4, '1/4'), (5, '1/2'), (6, 'Ironman')])),
                ('city', models.CharField(max_length=255)),
                ('voivodeship', models.CharField(choices=[(1, 'dolnośląskie'), (2, 'kujawsko-pomorskie'), (3, 'lubelskie'), (4, 'lubuskie'), (5, 'łódzkie'), (6, 'małopolskie'), (7, 'mazowieckie'), (8, 'opolskie'), (9, 'podkarpackie'), (10, 'podlaskie'), (11, 'pomorskie'), (12, 'śląskie'), (13, 'świętokrzyskie'), (14, 'warmińsko-mazurskie'), (15, 'wielkopolskie'), (16, 'zachodniopomorskie')], max_length=50)),
                ('description', models.CharField(max_length=1500)),
                ('race_url', models.URLField()),
                ('participants', models.ManyToManyField(to='TriEvent_app.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'słabo'), (2, 'tak sobie'), (3, 'OK'), (4, 'fajnie'), (5, 'rewelacja')])),
                ('comment', models.TextField(max_length=500)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.race')),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swim', models.TimeField()),
                ('T1', models.TimeField()),
                ('bike', models.TimeField()),
                ('T2', models.TimeField()),
                ('run', models.TimeField()),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.athlete')),
                ('race_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TriEvent_app.race')),
            ],
        ),
    ]
