# Generated by Django 3.2.9 on 2021-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
