# Generated by Django 3.2.9 on 2021-11-26 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0003_alter_athlete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
