# Generated by Django 3.2.9 on 2021-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0004_race_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='username',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
