# Generated by Django 3.2.9 on 2021-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0005_athlete_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='username',
            field=models.CharField(default=True, max_length=255, unique=True),
        ),
    ]
