# Generated by Django 3.2.9 on 2021-12-04 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TriEvent_app', '0009_auto_20211129_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
