# Generated by Django 3.2.9 on 2021-12-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0010_alter_athlete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='player_name',
            new_name='athlete',
        ),
        migrations.RenameField(
            model_name='results',
            old_name='race_name',
            new_name='race',
        ),
    ]
