# Generated by Django 3.2.9 on 2021-12-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0011_auto_20211211_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='T1',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='results',
            name='T2',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='results',
            name='bike',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='results',
            name='run',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='results',
            name='swim',
            field=models.CharField(max_length=9),
        ),
    ]
