# Generated by Django 3.2.9 on 2021-12-11 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0013_auto_20211211_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='T1',
            field=models.TimeField(verbose_name='%HH:%MH:%SS'),
        ),
        migrations.AlterField(
            model_name='results',
            name='T2',
            field=models.TimeField(verbose_name='%HH:%MH:%SS'),
        ),
        migrations.AlterField(
            model_name='results',
            name='bike',
            field=models.TimeField(verbose_name='%HH:%MH:%SS'),
        ),
        migrations.AlterField(
            model_name='results',
            name='run',
            field=models.TimeField(verbose_name='%HH:%MH:%SS'),
        ),
        migrations.AlterField(
            model_name='results',
            name='swim',
            field=models.TimeField(verbose_name='%HH:%MH:%SS'),
        ),
    ]
