# Generated by Django 3.2.9 on 2021-12-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TriEvent_app', '0014_auto_20211211_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='T1',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='T2',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='bike',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='run',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='results',
            name='swim',
            field=models.TimeField(),
        ),
    ]
